import React from 'react';

const PrivacyPolicy = () => {
  return (
    <div className="max-w-3xl mx-auto px-4 py-10 text-gray-800">
      <h1 className="text-3xl font-bold mb-6">Privacy Policy</h1>
      <p className="mb-4">
        At <strong>RapidShare</strong>, powered by Ask Scope, we are committed to protecting your privacy and handling your data with transparency and care. This Privacy Policy outlines how we collect, use, and protect the information you provide while using our file-sharing services.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">1. Information Collection</h2>
      <p className="mb-4">
        When you access a file-sharing link generated by our CRM system, we collect your email for verification purposes. During the upload process, we collect file metadata such as file title, upload time, and access type (download or view-only).
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">2. File Access & Retention</h2>
      <p className="mb-4">
        Uploaded files are stored securely and are accessible to the CRM and the uploading client. Files are automatically deleted after <strong>60 days</strong> from the upload date unless manually retrieved. Deleted files move to a trash folder where they can be restored within <strong>30 days</strong> before permanent deletion.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">3. Email Notifications</h2>
      <p className="mb-4">
        We send automated email notifications 3 days before the scheduled deletion of any file from your account or trash folder.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">4. Data Security</h2>
      <p className="mb-4">
        We implement industry-standard security measures to safeguard your files and personal data. Only authorized personnel and the designated CRM have access to your uploaded content.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">5. Third-party Services</h2>
      <p className="mb-4">
        Your data is not shared with any third parties without your consent. All backend operations are securely handled via our Loop Ask Scope environment.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">6. Contact</h2>
      <p className="mb-4">
        If you have any questions about our Privacy Policy or your data, please contact us through our official Ask Scope channels.
      </p>
    </div>
  );
};

export default PrivacyPolicy;
